/**
 * Text exports: the historic C / JSON blocks and the ESPHome lambda.
 *
 * Byte-for-byte ports of `magcal/serialization.py` and `magcal/esphome.py`: the expected
 * strings live in `web/tests/golden/python-golden.json`, produced by the Python tool, so a
 * formatting difference shows up as a hard test failure rather than a silent drift.
 */

import { formatGauss, formatSix } from "./format.js";

const SEPARATOR = "=".repeat(50);
const AXES = ["x", "y", "z"];

/** Return the `{constant name: value}` map used by the C code and the ESPHome lambda. */
export function constantValues(calibration) {
  const values = {};
  AXES.forEach((axis, index) => {
    values[`hard_iron_bias_${axis}`] = calibration.hardIron[index];
  });
  AXES.forEach((rowAxis, rowIndex) => {
    AXES.forEach((columnAxis, columnIndex) => {
      values[`soft_iron_bias_${rowAxis}${columnAxis}`]
        = calibration.softIron[rowIndex][columnIndex];
    });
  });
  return values;
}

/** Return the historic C code block (byte compatible with the original tool). */
export function renderCCode(calibration) {
  const { hardIron, softIron } = calibration;
  const lines = [
    `\n${SEPARATOR}`,
    "C Code for calibration parameters:",
    SEPARATOR,
    `float hard_iron_bias_x = ${formatSix(hardIron[0])};`,
    `float hard_iron_bias_y = ${formatSix(hardIron[1])};`,
    `float hard_iron_bias_z = ${formatSix(hardIron[2])};`,
    "",
    `double soft_iron_bias_xx = ${formatSix(softIron[0][0])};`,
    `double soft_iron_bias_xy = ${formatSix(softIron[0][1])};`,
    `double soft_iron_bias_xz = ${formatSix(softIron[0][2])};`,
    "",
    `double soft_iron_bias_yx = ${formatSix(softIron[1][0])};`,
    `double soft_iron_bias_yy = ${formatSix(softIron[1][1])};`,
    `double soft_iron_bias_yz = ${formatSix(softIron[1][2])};`,
    "",
    `double soft_iron_bias_zx = ${formatSix(softIron[2][0])};`,
    `double soft_iron_bias_zy = ${formatSix(softIron[2][1])};`,
    `double soft_iron_bias_zz = ${formatSix(softIron[2][2])};`,
    SEPARATOR,
  ];
  return `${lines.join("\n")}\n`;
}

/** Return the historic four-key JSON block. */
export function renderJsonBlock(calibration) {
  const payload = {
    hard_iron_bias: calibration.hardIron.map(Number),
    soft_iron_matrix: calibration.softIron.map((row) => row.map(Number)),
    magnetic_field_strength: Number(calibration.fieldStrength),
    unit: "microtesla",
  };
  return `\n${SEPARATOR}\nJSON format for calibration parameters:\n${SEPARATOR}\n`
    + `${JSON.stringify(payload, null, 4)}\n${SEPARATOR}\n`;
}

/**
 * Return the paste-ready ESPHome lambda computing the (true) heading.
 *
 * Mirrors `magcal.esphome.build_lambda`: the same layout, the same `atan2(0 - xm_cal,
 * ym_cal)` convention as `esphome_code.yaml`, and the same 12-significant-digit values.
 * Tilt compensation is not included (it needs an accelerometer).
 */
export function renderEsphomeLambda(calibration, { declination = null, indent = "        " } = {}) {
  const values = constantValues(calibration);
  const lines = [
    "// Calibration generated by calibrate.py",
    `float hard_iron_bias_x = ${formatGauss(values.hard_iron_bias_x)};`,
    `float hard_iron_bias_y = ${formatGauss(values.hard_iron_bias_y)};`,
    `float hard_iron_bias_z = ${formatGauss(values.hard_iron_bias_z)};`,
    "",
  ];
  AXES.forEach((rowAxis) => {
    AXES.forEach((columnAxis) => {
      const name = `soft_iron_bias_${rowAxis}${columnAxis}`;
      lines.push(`double ${name} = ${formatGauss(values[name])};`);
    });
    lines.push("");
  });
  lines.push(
    "// get values x,y,z and subtract the hard iron offset",
    "float xm_off = id(hmc5883l_x).state - hard_iron_bias_x;",
    "float ym_off = id(hmc5883l_y).state - hard_iron_bias_y;",
    "float zm_off = id(hmc5883l_z).state - hard_iron_bias_z;",
    "",
    "// multiply by the inverse soft iron offset",
    "float xm_cal = xm_off * soft_iron_bias_xx + ym_off * soft_iron_bias_yx"
      + " + zm_off * soft_iron_bias_zx;",
    "float ym_cal = xm_off * soft_iron_bias_xy + ym_off * soft_iron_bias_yy"
      + " + zm_off * soft_iron_bias_zy;",
    "",
    "float heading = atan2(0 - xm_cal, ym_cal);",
  );
  if (declination !== null && declination !== undefined) {
    lines.push(
      `float magnetic_declination = ${formatGauss(Number(declination))};`,
      "heading += magnetic_declination * PI / 180.0f;",
    );
  }
  lines.push(
    "if (heading < 0) { heading += 2*PI; }",
    "if (heading > 2*PI) { heading -= 2*PI; }",
    "return heading * 180/M_PI;",
  );
  return lines.map((line) => (line ? indent + line : "")).join("\n");
}

/** The twelve constant names shared by the C block and the ESPHome lambda. */
export const ESPHOME_CONSTANT_NAMES = [
  ...["x", "y", "z"].map((axis) => `hard_iron_bias_${axis}`),
  ...["x", "y", "z"].flatMap((row) => ["x", "y", "z"].map((column) => `soft_iron_bias_${row}${column}`)),
];

/**
 * Replace the twelve calibration constants inside an ESPHome YAML file.
 *
 * All-or-nothing, exactly like `magcal.esphome.update_esphome_file`: the patched text is
 * returned only when *every* constant was found, and the caller downloads it.  A browser
 * cannot write in place, so the original file is never touched and no `.bak` is needed.
 *
 * Returns `{ text, replacements }` and raises `ValueError` listing the missing constants.
 */
export function patchEsphomeYaml(text, calibration) {
  const values = constantValues(calibration);
  const missing = [];
  let updated = text;
  let replacements = 0;
  ESPHOME_CONSTANT_NAMES.forEach((name) => {
    const pattern = new RegExp(`(\\b${name}\\s*=\\s*)([^;]*)(;)`, "g");
    const found = (updated.match(pattern) || []).length;
    if (found === 0) {
      missing.push(name);
      return;
    }
    updated = updated.replace(pattern, (match, head, value, tail) => head
      + formatGauss(values[name]) + tail);
    replacements += found;
  });
  if (missing.length > 0) {
    throw new ValueError(
      `could not find these calibration constants: ${missing.sort().join(", ")}`,
    );
  }
  return { text: updated, replacements };
}
